manifest_version = "0.1.0"
name = "Compute@Edge default template for Rust"
description = "Default package template used by the Fastly CLI for Rust-based Compute@Edge projects."
authors = ["<oss@fastly.com>"]
language = "rust"
